#!/bin/bash

# Configure Nginx as reverse proxy
configure_nginx() {
    local domain="$1"
    local panel_port="$2"
    local cert_path="$CERT_DIR/$domain"

    log "Removing default site..."
    rm -f /etc/nginx/sites-enabled/default

    log "Creating site configuration..."

    cat > /etc/nginx/sites-available/$domain << EOF
# 3X-UI Panel Configuration
# Auto-generated by 3X-UI installer

# HTTP to HTTPS redirect
server {
    listen 80;
    server_name $domain;
    return 301 https://\$server_name\$request_uri;
}

# HTTPS server with SSL offloading
server {
    listen 443 ssl http2;
    server_name $domain;

    # SSL Configuration
    ssl_certificate $cert_path/fullchain.pem;
    ssl_certificate_key $cert_path/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    # Reverse proxy to 3X-UI panel
    location / {
        proxy_pass http://127.0.0.1:$panel_port;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
        proxy_redirect off;
    }
}
EOF

    log "Enabling site..."
    ln -sf /etc/nginx/sites-available/$domain /etc/nginx/sites-enabled/$domain

    log "Testing Nginx configuration..."
    if ! nginx -t 2>&1 | grep -q "syntax is ok"; then
        err "Nginx configuration test failed!"
        nginx -t
        exit 1
    fi

    info "Site: $domain"
    info "Proxy: http://127.0.0.1:$panel_port"

    log "Nginx configured"
}
